### Problem 1

Load "the original dataset" from https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html into a pandas dataframe. (Hints: pandas.read_csv can read in a tab-separated file and information on the columns can be obtained from the brief description through the link above) 
1. What is the output variable for this dataset? (i.e. which variable is the one that a data scientist would predict, using this dataset?)
2. All the other columns in the dataset are the attributes. For each attribute: compute the mean and the standard deviation. For all of the attributes together, create a correlation matrix (Using Pearson correlation coefficients). Please use numpy and scipy methods. Next, calculate a correlation matrix using the pandas method (your dataframe variable name).corr. Did you get the same values?
3. Does it make sense to calculate the mean and standard deviation for all of the columns? Is the correlation meaningful? Why or why not?
4. Why is the main diagonal of the correlation coefficient equal to a vector of ones? Justify your answer

In [2]:
import pandas as pd
import numpy as np
# Download the diabetes file, and save it in the working directory
# Read the text file into a pandas dataframe
diabetes_df = pd.read_csv("diabetes.txt", sep='\t')

#1. Y is the output variable for the dataframe. Y is a measure of how far the disease has progressed in 1 year after the initial data collection.

columns = set(diabetes_df.columns)
columns.remove("Y")
for column in columns:
    col_values = np.array(diabetes_df[column])
    # calculate the mean and std for each attribute
    print(column, "\n std:", np.std(col_values), "\n mean:", np.mean(col_values))
    # calculate the standard deviation
    np.std(col_values)
    
# calculate the correlation coefficient matrix
print("Correlation coefficient matrix (computed with numpy):") 
display(pd.DataFrame(np.corrcoef(np.array(diabetes_df).T),columns = diabetes_df.columns))

print("Correlation coefficient matrix (computed with pandas):")
display(diabetes_df.corr())

BP
 std: 13.815628311857534
 mean: 94.64701357466062
SEX
 std: 0.4989957359922028
 mean: 1.4683257918552035
S1
 std: 34.568880126921364
 mean: 189.14027149321268
S4
 std: 1.288989285051803
 mean: 4.070248868778281
AGE
 std: 13.094190207980025
 mean: 48.51809954751131
S6
 std: 11.48332247173548
 mean: 91.26018099547511
S3
 std: 12.919562419379737
 mean: 49.78846153846154
BMI
 std: 4.413120855492464
 mean: 26.37579185520362
S5
 std: 0.5217992869003063
 mean: 4.641410859728507
S2
 std: 30.378657550243798
 mean: 115.43914027149322
Correlation coefficient matrix (computed with numpy):

,AGE,SEX,BMI,BP,S1,S2,S3,S4,S5,S6,Y
0,1.000000,0.173737,0.185085,0.335428,0.260061,0.219243,-0.075181,0.203841,0.270774,0.301731,0.187889
1,0.173737,1.000000,0.088161,0.241010,0.035277,0.142637,-0.379090,0.332115,0.149916,0.208133,0.043062
2,0.185085,0.088161,1.000000,0.395411,0.249777,0.261170,-0.366811,0.413807,0.446157,0.388680,0.586450
3,0.335428,0.241010,0.395411,1.000000,0.242464,0.185548,-0.178762,0.257650,0.393480,0.390430,0.441482
4,0.260061,0.035277,0.249777,0.242464,1.000000,0.896663,0.051519,0.542207,0.515503,0.325717,0.212022
5,0.219243,0.142637,0.261170,0.185548,0.896663,1.000000,-0.196455,0.659817,0.318357,0.290600,0.174054
6,-0.075181,-0.379090,-0.366811,-0.178762,0.051519,-0.196455,1.000000,-0.738493,-0.398577,-0.273697,-0.394789
7,0.203841,0.332115,0.413807,0.257650,0.542207,0.659817,-0.738493,1.000000,0.617859,0.417212,0.430453
8,0.270774,0.149916,0.446157,0.393480,0.515503,0.318357,-0.398577,0.617859,1.000000,0.464669,0.565883
9,0.301731,0.208133,0.388680,0.390430,0.325717,0.290600,-0.273697,0.417212,0.464669,1.000000,0.382483
10,0.187889,0.043062,0.586450,0.441482,0.212022,0.174054,-0.394789,0.430453,0.565883,0.382483,1.000000

Correlation coefficient matrix (computed with pandas):

,AGE,SEX,BMI,BP,S1,S2,S3,S4,S5,S6,Y
AGE,1.000000,0.173737,0.185085,0.335428,0.260061,0.219243,-0.075181,0.203841,0.270774,0.301731,0.187889
SEX,0.173737,1.000000,0.088161,0.241010,0.035277,0.142637,-0.379090,0.332115,0.149916,0.208133,0.043062
BMI,0.185085,0.088161,1.000000,0.395411,0.249777,0.261170,-0.366811,0.413807,0.446157,0.388680,0.586450
BP,0.335428,0.241010,0.395411,1.000000,0.242464,0.185548,-0.178762,0.257650,0.393480,0.390430,0.441482
S1,0.260061,0.035277,0.249777,0.242464,1.000000,0.896663,0.051519,0.542207,0.515503,0.325717,0.212022
S2,0.219243,0.142637,0.261170,0.185548,0.896663,1.000000,-0.196455,0.659817,0.318357,0.290600,0.174054
S3,-0.075181,-0.379090,-0.366811,-0.178762,0.051519,-0.196455,1.000000,-0.738493,-0.398577,-0.273697,-0.394789
S4,0.203841,0.332115,0.413807,0.257650,0.542207,0.659817,-0.738493,1.000000,0.617859,0.417212,0.430453
S5,0.270774,0.149916,0.446157,0.393480,0.515503,0.318357,-0.398577,0.617859,1.000000,0.464669,0.565883
S6,0.301731,0.208133,0.388680,0.390430,0.325717,0.290600,-0.273697,0.417212,0.464669,1.000000,0.382483
Y,0.187889,0.043062,0.586450,0.441482,0.212022,0.174054,-0.394789,0.430453,0.565883,0.382483,1.000000

The main diagonal of the correlation coefficient is equal to a vector of ones because every variable has full correlation with itself. 

3. It does not truly make sense to calculate the mean or standard deviation for the SEX column. It is a categorical variable, and thus mean does not make sense. Furthermore, standard deviation is not useful, since there are no values besides 1 and 2.

### Problem 2

###### Part 1: Predict the values of the output variable you identified above.
1. Normalize all columns which it makes sense to normalize
2. Separate the entries into train and test segments randomly. Have the train segment contain 80%, about 354 entries. Let the test segment contain the remaining entries.
3. Use scikit-learn's linear regression algorithm to train on two columns of the train set, and test on the test set.
4. Use the linear regression algorithm to train on all the columns of the train set, and test on the test set.
5. Try different combinations of columns. See if you can find any combination that is better than using all of the columns.
6. Based on the values of MSE or R-squared of the train set and test set, what combination do you think is the best?

In [175]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

# It does not make sense to use linear regression on the sex column, so we drop it
lin_diab_view = diabetes_df.drop(columns = ['SEX'])

# normalize the values, 
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
y_scaler = StandardScaler()
y = lin_diab_view["Y"]
X = lin_diab_view.drop(columns = ["Y"])
saved_cols = X.columns
lin_diab_view_arr = scaler.fit_transform(X)
normalized_dataset = pd.DataFrame(lin_diab_view_arr, columns = saved_cols)
y_norm = y_scaler.fit_transform(np.array(y).reshape(-1,1))
normalized_output = pd.DataFrame(y_norm,columns=["Y"])
display(normalized_dataset)

# separate entries into train and test segments
from sklearn.model_selection import train_test_split

train, test = train_test_split(lin_diab_view, test_size=0.2)
train_X = train.drop(columns = ["Y"])
train_y = train["Y"]
test_X = test.drop(columns = ["Y"])
test_y = test["Y"]

# Create linear model and train and test for two columns
from sklearn.linear_model import LinearRegression
diab_pred = LinearRegression().fit(train_X[["AGE", "BP"]], train_y)

print("Scores for Age and Blood Pressure:")
print(f"R2 values for the train set: {diab_pred.score(test_X[['AGE', 'BP']], test_y)}")
print(f"Mean Squared Error (MSE) value for the train set: {mean_squared_error(train_y,diab_pred.predict(train_X[['AGE', 'BP']]))}")
print(f"R2 values for the test set: {diab_pred.score(test_X[['AGE', 'BP']], test_y)}")
print(f"MSE value for the test set: {mean_squared_error(test_y,diab_pred.predict(test_X[['AGE', 'BP']]))}\n")


# Test for all columns
diab_pred = LinearRegression().fit(train_X, train_y)

print("Testing for all the columns:")
print(f"R2 values for the train set: {diab_pred.score(train_X,train_y)}")
print(f"MSE value for the train set: {mean_squared_error(train_y,diab_pred.predict(train_X))}")
print(f"R2 values for the test set: {diab_pred.score(test_X, test_y)}")
print(f"MSE value for the test set: {mean_squared_error(test_y,diab_pred.predict(test_X))}\n")

# Sample train and test sets from the normalized dataset
train_X, test_X, train_y, test_y = train_test_split(normalized_dataset, normalized_output, test_size=0.2)

# test for two columns on the normalized dataset
diab_pred = LinearRegression().fit(train_X[["AGE", "BP"]], train_y)

print("Scores for Age and Blood Pressure after normalization")
test_preds = diab_pred.predict(test_X[['AGE', 'BP']])
train_preds = diab_pred.predict(train_X[['AGE', 'BP']])
print(f"R2 values for the train set: {diab_pred.score(train_X[['AGE', 'BP']], train_y)}")
print(f"Mean Squared Error (MSE) value for the train set: {mean_squared_error(y_scaler.inverse_transform(train_y.astype(float)),y_scaler.inverse_transform(train_preds.astype(float)))}")
print(f"R2 values for the test set: {diab_pred.score(test_X[['AGE', 'BP']], test_y)}")
print(f"MSE value for the test set: {mean_squared_error(y_scaler.inverse_transform(test_y.astype(float)),y_scaler.inverse_transform(test_preds.astype(float)))}\n")

# test for all columns on the normalized dataset
diab_pred = LinearRegression().fit(train_X, train_y)

print("Scores for all columns after normalization")
test_preds = diab_pred.predict(test_X)
train_preds = diab_pred.predict(train_X)
print(f"R2 values for the train set: {diab_pred.score(train_X, train_y)}")
print(f"Mean Squared Error (MSE) value for the train set: {mean_squared_error(y_scaler.inverse_transform(train_y.astype(float)),y_scaler.inverse_transform(train_preds.astype(float)))}")
print(f"R2 values for the test set: {diab_pred.score(test_X, test_y)}")
print(f"MSE value for the test set: {mean_squared_error(y_scaler.inverse_transform(test_y.astype(float)),y_scaler.inverse_transform(test_preds.astype(float)))}\n")

,AGE,BMI,BP,S1,S2,S3,S4,S5,S6
0,0.800500,1.297088,0.459841,-0.929746,-0.732065,-0.912451,-0.054499,0.418531,-0.370989
1,-0.039567,-1.082180,-0.553505,-0.177624,-0.402886,1.564414,-0.830301,-1.436589,-1.938479
2,1.793307,0.934533,-0.119214,-0.958674,-0.718897,-0.680245,-0.054499,0.060156,-0.545154
3,-1.872441,-0.243771,-0.770650,0.256292,0.525397,-0.757647,0.721302,0.476983,-0.196823
4,0.113172,-0.764944,0.459841,0.082726,0.327890,0.171178,-0.054499,-0.672502,-0.980568
...,...,...,...,...,...,...,...,...,...
437,0.876870,0.413360,1.256040,-0.119769,-0.053957,-0.602843,-0.054499,0.655787,0.151508
438,-0.115937,-0.334410,-1.422086,1.037341,1.664355,-0.602843,0.721302,-0.380819,0.935254
439,0.876870,-0.334410,0.363573,-0.785107,-0.290965,-0.525441,-0.232934,-0.985649,0.325674
440,-0.956004,0.821235,0.025550,0.343075,0.321306,-0.602843,0.558384,0.936163,-0.545154
441,-0.956004,-1.535374,-1.711613,1.760535,0.584649,3.654268,-0.830301,-0.088752,0.064426

Scores for Age and Blood Pressure:
R2 values for the train set: 0.08806525156513467
Mean Squared Error (MSE) value for the train set: 4421.417546851749
R2 values for the test set: 0.08806525156513467
MSE value for the test set: 6149.704334483517

Testing for all the columns:
R2 values for the train set: 0.5002757477348453
MSE value for the train set: 2860.764792639588
R2 values for the test set: 0.4688569167712323
MSE value for the test set: 3581.8055258546733

Scores for Age and Blood Pressure after normalization
R2 values for the train set: 0.20762066949984193
Mean Squared Error (MSE) value for the train set: 4745.620010311854
R2 values for the test set: 0.14415824622259144
MSE value for the test set: 4860.789166267863

Scores for all columns after normalization
R2 values for the train set: 0.4979334321715667
Mean Squared Error (MSE) value for the train set: 3006.9148185519607
R2 values for the test set: 0.4989059816216955
MSE value for the test set: 2845.9845118147664

I was mistaken before. 
This is an R^2 value, which means a higher value means the model is better.
Thus, the result for regressing on all columns is better than for Age and Blood Pressure.

###### Part 2: Use Linear Regression on Quadratic Features
Use sklearn.preprocessing.PolynomialFeatures to expand the data set to include nonlinear elements, then perform linear regression again. Is this a better model comparing with the one you find in part 1?

reference:https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html

In [74]:
from sklearn.preprocessing import PolynomialFeatures
poly_transform = PolynomialFeatures(2)

In [196]:
# Sample the train and test sets
train, test = train_test_split(lin_diab_view, test_size=0.2)
train_X = train.drop(columns = ["Y"])
train_y = train["Y"]
test_X = test.drop(columns = ["Y"])
test_y = test["Y"]

# Transform lin_diab_view to have nonlinear interaction 
X = lin_diab_view.drop(columns = ["Y"])
poly_diab_view = poly_transform.fit(X)
p_train_X = poly_diab_view.transform(train_X)
p_test_X = poly_diab_view.transform(test_X)

p_diab_pred = LinearRegression().fit(p_train_X, train_y)

print("Testing for all polynomial expansions of the features for degree <= 2")
print(f"R2 values for the train set: {p_diab_pred.score(p_train_X,train_y)}")
print(f"MSE value for the train set: {mean_squared_error(train_y,p_diab_pred.predict(p_train_X))}")
print(f"R2 values for the test set: {p_diab_pred.score(p_test_X, test_y)}")
print(f"MSE value for the test set: {mean_squared_error(test_y,p_diab_pred.predict(p_test_X))}")

p_train_X, p_test_X, train_y, test_y = train_test_split(normalized_dataset, normalized_output, test_size=0.2)
p_diab_pred = LinearRegression().fit(p_train_X, train_y)
test_preds = p_diab_pred.predict(p_test_X)
train_preds = p_diab_pred.predict(p_train_X)

print("Testing for all polynomial expansions of the  normalized features for degree <= 2")
print(f"R2 values for the train set: {p_diab_pred.score(p_train_X,train_y)}")
print(f"MSE value for the train set: {mean_squared_error(y_scaler.inverse_transform(train_y.astype(float)),y_scaler.inverse_transform(train_preds.astype(float)))}")
print(f"R2 values for the test set: {p_diab_pred.score(p_test_X, test_y)}")
print(f"MSE value for the test set: {mean_squared_error(y_scaler.inverse_transform(test_y.astype(float)),y_scaler.inverse_transform(test_preds.astype(float)))}")

Testing for all polynomial expansions of the features for degree <= 2
R2 values for the train set: 0.5858869163080647
MSE value for the train set: 2452.080193105157
R2 values for the test set: 0.33117470237819546
MSE value for the test set: 3941.118378238467
Testing for all polynomial expansions of the  normalized features for degree <= 2
R2 values for the train set: 0.4999099415182334
MSE value for the train set: 2909.1657113310257
R2 values for the test set: 0.48055865657038
MSE value for the test set: 3204.917808132228

###### Notice that for the polynomial factor expansion in this case, the result varies widely with different samplings of the train and test set. In part, this is because we have such a small set with respect to the number of features. When you have many features and a small dataset, you run the risk of overfitting. 

###### Note as well, that the normalized model in this case does not show nearly as much instability